### ISSUE TITLE
Migrate Firefox for Android (Beta) to Pontoon

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#101]
Next merge day: 20 September
## Shipping locales

- [ ] ach
- [ ] an
- [ ] ar
- [ ] as
- [ ] bn-BD
- [ ] br
- [ ] bs
- [ ] ca
- [ ] cak
- [ ] cy
- [ ] dsb
- [ ] en-ZA
- [ ] eu
- [ ] fa
- [ ] ff
- [ ] ga-IE
- [ ] gd
- [ ] gn
- [ ] hi-IN
- [ ] hr
- [ ] hsb
- [ ] hu
- [ ] hy-AM
- [ ] is
- [ ] kk
- [ ] kn
- [ ] lt
- [ ] mai
- [ ] ml
- [ ] mr
- [ ] ne-NP
- [ ] or
- [ ] pt-PT
- [ ] ro
- [ ] son
- [ ] ta
- [ ] ur
- [ ] uz
- [ ] xh
- [ ] zam

## Close-to-shipping locales
- [ ] trs
- [ ] meh
- [ ] quy
- [ ] hto
- [ ] qvi
- [ ] pbb
- [ ] mix
- [ ] hto
- [ ] pai

**Comment by flodolo** [comment]
There is no such product on Pontoon (on purpose). Should we just close this one?

**Comment by Delphine** [comment]
Yes, closing.
