### ISSUE TITLE
Migrate Focus for Android to Pontoon

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#103]
Given the information about the next deadline for this project, it is the assignee's decision when to schedule the migration for this project so that it does not add risk to its l10n delivery.

Next release date: TBD

## Shipping locales

- [x] ar
- [x] ca
- [x] cy
- [x] dsb
- [x] ga-IE
- [x] hsb
- [x] ta

## Locales in progress

- [x] eu
- [x] ne-NP

**Comment by Delphine** [comment]
Added "eu" to locales in progress. Spoke with Julen offline, he'd prefer doing this before the migration.

**Comment by Delphine** [comment]
I'm thinking I can do this asap. I'll send a mail + dev.l10n message today for a migration next Tues/Wed.
Next l10n string export for this should be next Thurs. Then there's a 2 week cycle starting.

**Comment by Delphine** [comment]
Nevermind, I'm traveling Wed. Tues would be better.

**Comment by Delphine** [comment]
Sent initial email to all managers of locales listed here.
Posted entire mobile schedule on dev.l10n: https://groups.google.com/forum/#!topic/mozilla.dev.l10n/906xzujhdsk

**Comment by Delphine** [comment]
Done \o/
