### ISSUE TITLE
Migrate Focus for iOS to Pontoon

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#104]
Given the information about the next deadline for this project, it is the assignee's decision when to schedule the migration for this project so that it does not add risk to its l10n delivery.

Next release date: TBD

## Shipping locales

- [x] af
- [x] ar
- [x] br
- [x] ca
- [x] cy
- [x] dsb
- [x] eu
- [x] fa
- [x] ga-IE
- [x] gd
- [x] hi
- [x] hsb
- [x] is
- [x] kk
- [x] pt-PT
- [x] son
- [x] ta
- [x] uz

## Locales in progress

- [x] kn
- [x] ne

**Comment by Delphine** [comment]
Given we're working on 2 week cycles now, this is going to be hard for both Focus'. Whatever moment I choose, I feel like it's going to have a negative impact on the workflow one way or another, unfortunately.
Right now for Focus iOS we're waiting on strings (should be today), maybe tomorrow. Then there's a 2 week cycle until l10n delivery (August 17th). So I'd like to wait until maybe some time end of next week to migrate this one. I'll start sending out emails once I'm 100% sure I want to do this way (probably later today or tomorrow I'll know for sure).

**Comment by Delphine** [comment]
Sent initial email to all managers of locales listed here.
Posted entire mobile schedule on dev.l10n: https://groups.google.com/forum/#!topic/mozilla.dev.l10n/906xzujhdsk

**Comment by Delphine** [comment]
Migration done!

**Comment by Delphine** [comment]
(for the record: we decided to move this project earlier and announced it. More details from me in this thread: https://groups.google.com/forum/#!topic/mozilla.dev.l10n/qGHQssi8Qaw)
