### ISSUE TITLE
Migrate Thunderbird (Nightly) to Pontoon

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#106]
Given the information about the next deadline for this project, it is the assignee's decision when to schedule the migration for this project so that it does not add risk to its l10n delivery.

Next merge day: Sep 20

## Shipping locales

- [x] af
- [x] an
- [x] ar
- [x] br
- [x] bs
- [x] ca
- [x] cy
- [x] dsb
- [ ] en-ZA
- [x] eu
- [x] fa
- [x] ga-IE
- [x] gd
- [x] hr
- [x] hsb
- [x] hu
- [x] hy-AM
- [x] kk
- [x] lt
- [x] pt
- [x] ro
- [x] uz

## Locales in-progress

- [ ] am
- [ ] roa-ES-val
- [ ] sm

**Comment by flodolo** [comment]
Adding af to the list (it's missing), keeping en-ZA out for now.

**Comment by flodolo** [comment]
Wrong issue…
