### ISSUE TITLE
Migrate Seamonkey (Nightly) to Pontoon

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#108]
Given the information about the next deadline for this project, it is the assignee's decision when to schedule the migration for this project so that it does not add risk to its l10n delivery.

Next merge day: Sep 20

## Shipping locales

- [ ] en-ZA
- [x] lt
- [x] pt-PT

**Comment by flodolo** [comment]
Keeping en-ZA on hold, pending discussion with Dwayne.
