### ISSUE TITLE
Communications for Pudelo

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#109]
## Announcement
- [x] Blog post
- [x] Mailing list
- [x] Twitter
- [x] Facebook
- [x] Community call
- [x] Telegram/IRC

## Schedule
- [x] Write email for mailing list with schedule & request to clear pending suggestions
- [x] Write email for individual communities who aren't subscribed to the mailing list

**Comment by flodolo** [comment]
(I guess we can close this one, reopen if that's not the case)
