### ISSUE TITLE
Perform database dump of Pootle

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#110]
Perform a database dump of the MLO instance of Pootle. Analyze the data for patterns and the ability to use it in our infrastructure.

**Comment by flodolo** [comment]
I'm doing it every few days, keeping local copies. One copy was shared with @pike, not sure if the results of his tests where successful.

**Comment by Pike** [comment]
In fact, they were not. I can get the data hooked up to a local pootle install and load it, but I don't get it. The models don't have comments, and the data in particular around history and time isn't obvious.

**Comment by flodolo** [comment]
Noted today that DB shrinks when we remove locales and projects. I've started downloading daily dumps locally (they only keep a week on the server), but I might not be able to do it consistently. Also not sure it makes sense to clog our Drive uploading them (it takes a while).

**Comment by flodolo** [comment]
All projects are now disabled on Pootle, please ping me if someone wants to take another look before the server is shut down for good.
