### ISSUE TITLE
Calendar schedule for projects migration from Pootle to Pontoon

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#111]
We need a calendar for the community to be aware of when all migrations will take place, at a glance. The projects we have are:

| Product | Scheduled Migration Date | Next Milestone |
| --- | --- | --- |
| Firefox (Nightly) | Aug 21 (shipping locales) | Sep 20 |
| Firefox (Beta) | Aug 21 (shipping locales) | Sep 13 |
| Firefox for Android (Nightly) | Aug 21 | Sep 20 |
| Firefox for iOS | Aug 8 | - |
| Firefox Health Report | Aug 7 | - |
| Focus for Android | Aug 8 | - |
| Focus for iOS | Aug 11 | - |
| Lightning (Nightly) | Aug 23 | Sep 20 |
| mozilla.org | Aug 8 (Asunción locales)<br>Aug 21 (others) | - |
| Seamonkey (Nightly) | Aug 23 | Sep 20 |
| Thunderbird (Nightly) | Aug 23 | Sep 20 |

What are the dates of these projects' next milestones? Merge day for m-c is 20 September (that covers Firefox, Fx Android). Need dates for the rest.

**Comment by gueroJeff** [comment]
@peiying2 @flodolo @Delphine When you have time, please update the original comment in this issue with the date you have chosen to perform the migrations of your assigned projects. The sooner we have this, the better, so that we can communicate out the full migration schedule to the communities at once and only follow up with reminders as the dates get closer.

**Comment by flodolo** [comment]
I've already added mine to the schedule.

**Comment by Delphine** [comment]
I still need to figure out Firefox iOS. Otherwise I think I'm set (updated my other projects)

**Comment by Delphine** [comment]
Done for mobile projects.

**Comment by peiying2** [comment]
Update mine.  I will target on two days, Aug 8 for communities of locales that need training at Asunción and the rest on Aug 17.

**Comment by roshangm1** [comment]
Migration will take place for all the locales or for some only ?
Any list of locales whose projects will be migrated on the first phase ?
Thank You.

**Comment by flodolo** [comment]
> Migration will take place for all the locales or for some only ?

For products we'll migrate locales that are shipping (ne-NP is one of them), then we'll look into locales that have a good activity.

You can find list of locales in individual issues (one per product)
https://github.com/mozilla-l10n/pm-projects/projects/14
