### ISSUE TITLE
Clean up the list of locales in mozilla.org

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/pm-projects#12]
We need to clean up the list of locales in mozilla.org, both on stage and production.

List of locales on stage
https://github.com/mozilla-l10n/langchecker/blob/master/app/config/locales.inc.php#L8-L23

List of locales on production
https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L120-L132

**Comment by flodolo** [comment]
I'm going to take care of the actual removal, but assign this first to @peiying2 to identify which locales we can remove in the post Firefox OS era

**Comment by flodolo** [comment]
We're removing brx, kok, ks, and sat from aurora builds, we should clean up mozilla.org too

**Comment by flodolo** [comment]
Adding Belarusian (be) to the list. I'll start removing these 5 from Bedrock (if enabled on production) and tools

**Comment by flodolo** [comment]
List of Firefox OS locales: 'bm', 'ee', 'es', 'ha', 'ig', 'ln', 'mg', 'sw', 'tl', 'tn', 'wo', 'yo'.

**Comment by flodolo** [comment]
Cleaned up locales on mozilla.org, langchecker, repositories.

Only pending one https://github.com/mozilla-l10n/stores_l10n/pull/72, in order to confirm if removing Belarusian is going to create problem on reldrivers' side.

**Comment by peiying2** [comment]
Those FFOS locales are correct.  Thanks for getting this done.
