### ISSUE TITLE
Post announcing the pilot

### ISSUE THREAD

**Issue by nukeador** [mozilla-l10n/pm-projects#120]
Post explaining the pilot and setting the expectations with community.

- [Working doc](https://docs.google.com/document/d/1zPgAL4ZWVyTQ_n5UdfG-iuUObsR6rO6snnBKUHDQ5j8/edit#)

**Comment by nukeador** [comment]
@gueroJeff I can draft something and share with the team.

**Comment by gueroJeff** [comment]
sgtm

**Comment by nukeador** [comment]
@gueroJeff I did a first pass here, please chime in and add any feedback https://docs.google.com/document/d/1zPgAL4ZWVyTQ_n5UdfG-iuUObsR6rO6snnBKUHDQ5j8/edit#

**Comment by nukeador** [comment]
[Published on discourse](https://discourse.mozilla.org/t/leadership-shared-agreements-and-localization/25682)
