### ISSUE TITLE
Bringing clarity to role definitions

### ISSUE THREAD

**Issue by nukeador** [mozilla-l10n/pm-projects#126]
## Goal

Co-creating role descriptions for l10n community roles

## Roles

* Responsible: @gueroJeff @nukeador
* Accountable: @gueroJeff @nukeador
* Consulted: Pilot team
* Informed: Contributors

## Actions

- [x] Internal document about current roles (R: @gueroJeff Date: 13/3)

### Survey
- [x] [Survey for contributors created](https://docs.google.com/document/d/1PJKCEdX_C3gD48wXqN-MEhPVMm2QPThL03FmurQWSFo/edit#) (R: @gueroJeff @nukeador Date: 12/3)
- [x] Survey distributed (R: @gueroJeff Date: 19/3)
- [x] Survey data summarized (R: @gueroJeff Date: 9/4)

### Discussion
- [x] Consolidate role definitions (R: Date: 13/4)
- [x] Input from everyone and agreement (R: Date: 17/4)
- [ ] Defining health metrics (R: Date: 17/4)

### Sharing
- [x] Blog post (R: Date: 18/4)
- [ ] Discourse post (R: Date: 18/4)
- [x] Mailing list (R: Date: 18/4)
- [x] Telegram (R: Date: 18/4)

**Comment by nukeador** [comment]
Updating timeline

**Comment by nukeador** [comment]
I've updated the timeline to reflect where we are this week. We still want to get more answers during this week to consolidate all the information.

**Comment by gueroJeff** [comment]
I'm trying to clean up the list of projects in the pm-projects repo. Since this has been inactive for nearly 2 years, can we close this?
