### ISSUE TITLE
Providing safe channels

### ISSUE THREAD

**Issue by nukeador** [mozilla-l10n/pm-projects#128]
## Goal

Create safe channels for peer-support

## Roles

* Responsible: @Delphine @emmairwin 
* Accountable: @gueroJeff @nukeador
* Consulted: Pilot team
* Informed: 

## Actions

- [x] Define list of participants and validate them
- [x] Email and registration are defined
- [x] Telegram channel is created
- [x] Email and registration are sent out
- [ ] Identifying the topic + questions, and dates for discussion/interaction are documented for share-out (ETA: April 25)
- [ ] Moderators are identified (ETA: post April 25, can happen organically over the 4 weeks too)
- [ ] Invitations for participation in discussions are sent. (includes topics + question, dates, and telegram link + assurance of privacy) (ETA: April 27).
- [ ] Discussion 1 (ETA: May 1st). 
- [ ] Final survey is sent, analyzed and results shared (3 weeks later)
- [ ] Next steps communicated with all members of the group

**Comment by Delphine** [comment]
Link to our working spreadsheet, that has much more details: https://docs.google.com/document/d/1c3OTqTNa63KHqyBIcE0hhWtLxNH5Cc6Dh7qNjbpQpHU/edit#
(only accessible to Mozilla staff)

**Comment by gueroJeff** [comment]
I'm trying to clean up the list of projects in the pm-projects repo. Since this has been inactive for nearly 2 years, can we close this?
