### ISSUE TITLE
Amman Budget

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#133]
Budget should consist of the following costs:

- [x] Travel
- [x] Lodging (including breakfast)
- [x] Meals (2 lunch, 3 dinner)
- [x] Transportation
- [x] Visas
- [x] Venue
- [x] Gear
- [ ] Cultural activity

**Comment by gueroJeff** [comment]
Visa budget will be the usual amount (USD$60 per visa needed).

Gear has already been ordered and will depend on the number of people present.

Lodging and venue need to be the same place.

Travel budget will be determined once registration period has closed on July 8th. 

Need recommendations on transportation budget from community.
