### ISSUE TITLE
Amman Goals and Agenda

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#135]
# Core focus:
- Discuss current state of the community.
- Localization guidelines and good practice
- Go over the new CPG guidelines.

# Outcomes:
- Localizers are all on the same page concerning l10n processes and best practices.
- Each community's language resources (style guides, term lists) are created & up-to-date.
- Marked improvement in localization quality for l10n projects.
- Localizers trained in translation process best practices.
- CPG is understood and enforced

# Format:
## Day 1:
**Morning**
- 
- 

**Afternoon**
- 
- 
## Day 2:
- 
- 

# Planning:
The l10n-drivers will coordinate among l10n communities to identify common goals.
(TBD)

**Comment by gueroJeff** [comment]
https://wiki.mozilla.org/L10n:Meetings/2018_Arabic_Meetup
