### ISSUE TITLE
Jakarta Logistics

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#140]
- [x] Hotel reservations for community: https://goo.gl/maps/E2wczf4t3AM2 Puri Denpasar Hotel
- [x] Community Space reserved
- [x] Catering reservation
- [x] Find and book restaurants
- [x] Transportation for non-local community members
- [x] Create Wiki for the event
- [x] Update wiki with all information needed
- [x] Get name tags and gear for localizers
- [x] Create Telegram group.

**Comment by Delphine** [comment]
Wiki can be found here: https://wiki.mozilla.org/L10n:Meetings/2018_Jakarta_Rocket_Sprint
Next step is to update it with all needed information

**Comment by peiying2** [comment]
- Hotel reservation (include breakfast) to be done by early next week (Kiki)
- Catering will be reserved soon (box lunch) (Lidya)
- Transportation info from airport, train and bus station to hotel and Moz Space to be updated on wiki (Fauzan)
- Dinner reservations (Ina)

**Comment by kelimuttu** [comment]
Hotel reservation done!

**Comment by Delphine** [comment]
We have a Telegram group for planning. Next step is to create another one with only participants of event and invite them

**Comment by Delphine** [comment]
Seems like this is done. Moving to Done section
