### ISSUE TITLE
Jakarta Budget

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#141]
[x] Hotel
[x] Meals
[x] Transportation (non-Jakarta residents)
[x] Cultural activity
[x] Local transportation

**Comment by Delphine** [comment]
Jakarta budget form can be found here: https://docs.google.com/spreadsheets/d/1x9UZ3KF4-RfqXURxlCIKyLITN8YECQEBx7RIxVoxJ7g/edit#gid=681717703

**Comment by peiying2** [comment]
- Meal cost can be estimated based on average *dinner cost*/pp in Jakarta x 5 (3 dinners x 2 lunches) = meal budget/pp. 
- Transportation budget is based on actual if travel plan changes (train to plane or plane to train).

**Comment by peiying2** [comment]
- Advance payment will be paid by the Mozilla Indonesia budget for hotel reservation, lunch catering or any other cash upfront payment. L10n team will pay in full during the event.

**Comment by peiying2** [comment]
Karaoke at Moz Space is the cultural activity
