### ISSUE TITLE
Jakarta Invitations:

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#142]
[x] Invitees were selected by the communities, including people from Wikimedia. 
[x] Registration form was created and sent
[x] Registration complete

**Comment by Delphine** [comment]
Just one person is missing from the internal Mozilla registration form. Fauzan to get in touch this week with the missing person who still needs to register from @peiying2's registration form.

**Comment by peiying2** [comment]
This status has not changed despite of Fauzan reaching out a few different ways. This should not block us from making reservations. We can add more people if need be.
