### ISSUE TITLE
Paris Logistics

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#152]
- [x] **P1** Identify visa needs.
- [x] **P1** Identify & book hotel for localizers
- [x] **P1** Identify & book venue for localizers
- [x] **P1** Book travel for localizers
- [x] **P2** Find & book restaurants or catering for 2 lunches & 2 dinners.
- [x] **P2** Identify transportation needs and make necessary arrangements.
- [x] **P2** Identify possible cultural activities.
- [x] **P3**Create Wiki for the event.
- [x] **P3** Get name tags and gear for localizers.
- [x] **P4** Create Telegram group.

**Comment by Delphine** [comment]
Venue identified and booked: reserved Salle des fêtes in Paris office. Also, Service Now request is on file (put Flod, Matjaz and Adrian's contact in their specifying to reach out to them if needed while I'm off on PTO)

**Comment by Delphine** [comment]
We'll do an Escape Room! Good for team bonding, thanks for the idea Adrian :)

Here are some places I will contact and choose from:
* The Game (https://www.thegame-france.com/en/index.htm) - Fun rooms to do there are : le métro, l’avion, Assassin’s Creed. Don't do le braquage de banque!
* L’académie Lock (https://lockacademy.com) - Fun rooms to do there are : salles du meurtre du doyen de l’académie, or la disparition de la fille de Sherlock
* Prizoners (https://www.prizoners.com/paris/)

**Comment by flodolo** [comment]
I took a very quick look, and they all seem super booked around those dates. Also, not completely sure the last one has English versions?
