### ISSUE TITLE
[bn] Consolidate legal docs to one version

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/pm-projects#161]
- Create a set for bn
- Implementation takes place after mozilla.org switch to bn.

**Comment by flodolo** [comment]
We should also:
- Compare the translated versions of the same document, to check how many differences there are. I've checked one (Cloud), and it's the same document for both languages.
- Check with legal if the localized versions are legally binding in some form.

**Comment by flodolo** [comment]
We should also:
- Compare the translated versions of the same document, to check how many differences there are. I've checked one (Cloud), and it's the same document for both languages.
- Check with legal if the localized versions are legally binding in some form.

**Comment by peiying2** [comment]
As discussed, the two versions are identical in all the docs. This was decided by legal team from the beginning. There is no legal issue involved by having one version.
* File an issue: https://github.com/mozilla/legal-docs/issues/1248
* Create a `bn` folder for all docs that have one version or both versions.
* Once mozilla.org `bn` version is set up, legal docs and the website will be rolled out to production at the same time.

**Comment by flodolo** [comment]
@peiying2 
Do you know when the changes are going to be pushed to production?

I'm working on the mozilla.org bits https://github.com/mozilla-l10n/pm-projects/issues/165

**Comment by flodolo** [comment]
This is now done and in production.
