### ISSUE TITLE
[bn] Unify web projects

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/pm-projects#167]
Merge in favor of **bn-BD**
- [x] [AMO](https://github.com/mozilla/addons-server/issues/11816)
- [x] [Firefox Accounts](https://github.com/mozilla/fxa-content-server-l10n/issues/358)
- [x] [MDN](https://github.com/mozilla-l10n/mdn-l10n/issues/4)
- [x] [Thunderbird.net](https://github.com/thundernest/thunderbird.net-l10n/issues/1)

Merge in favor of **bn-IN**
- [x] [SUMO](https://github.com/mozilla-l10n/sumo-l10n/issues/6)

Move bn-BD
- [x] [AMO Frontend](https://github.com/mozilla/addons-frontend/issues/8336)
- [x] [AMO Linter](https://github.com/mozilla/addons-linter/issues/2696)
- [x] [Mozilla Activate](https://github.com/mozilla/activate.mozilla.community/issues/364)
- [x] [Mozillians](https://github.com/mozilla-l10n/mozillians-l10n/issues/3)

**Comment by flodolo** [comment]
Feel free to split the issue in multiple issues, as long as they're tracked in the project.

**Comment by flodolo** [comment]
I don't understand the question. All projects need to be moved from bn-BD
and bn-IN to bn, in the end those two locales should be removed because
they won't have any project left.

Il gio 11 lug 2019, 18:21 Peiying <notifications@github.com> ha scritto:

**Comment by gueroJeff** [comment]
@cocomo we're eliminating both bn-IN and bn-BD in favor of a single bn
locale. I suggest looking at which locale is most complete for the project
being migrated to bn and migrate that. If there are diffs in the project
list, then they just get moved to bn.

**Comment by peiying2** [comment]
OK, I will add too more products to this list. AMO covers 3 projects. They have different contacts.

**Comment by peiying2** [comment]
Almost there. SUMO and Mozillans are done (pending Pontoon migration). One more to go.

**Comment by peiying2** [comment]
SUMO product code push will be timed with the push article merge. It is scheduled for first Wed/Thu in September.

**Comment by peiying2** [comment]
All done!
