### ISSUE TITLE
[bn] Unify mobile projects

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/pm-projects#168]
bn-IN has Firefox Rocket, which is not available in bn-BD. We should move it under bn.

**Comment by Delphine** [comment]
@chianger Wanted you to be aware that we are going to merge bn-IN and bn-BD locales soon, into a generic Bangladesh, which is "bn" locale code (we're doing this for all our products, Firefox included).
For Firefox Lite, we'll be merging the existing localization into that new "bn" folder.
Not sure if you need to do anything on your side, such as changing the locale code or renaming the folder or such.

**Comment by chianger** [comment]
Thank you @Delphine I'll check with the team.

**Comment by chianger** [comment]
Can you share the schedule about when this merge will happen?

**Comment by Delphine** [comment]
I don't think we have a specific timeline for this, but it would be great to have all this wrapped up by the end of next week.

**Comment by chianger** [comment]
I see. Just to make sure I understand this correctly. l10n team will modify on l10n repo for following change, right:
app/src/main/res/values-bn-IN to modify to values-bn

**Comment by Delphine** [comment]
Right, once you've renamed app/src/main/res/values-bn-IN to values-bn, we can then pick that up on our side.

**Comment by Delphine** [comment]
@chianger I'm going to delete the bn folder on Pontoon today. Can we try to wrap this up today or Monday?

**Comment by Delphine** [comment]
This has been taken care of here: https://github.com/mozilla-l10n/zerda-android-l10n/pull/52
and now "bn" for Firefox Lite lives in Pontoon here: https://pontoon.mozilla.org/bn/firefox-rocket/
@chianger: asssuming you know have to set up things on your side. Please let me know and I can close this issue once it's done :) thanks!

**Comment by Delphine** [comment]
Confirmed on Slack that everything works perfectly on both sides.
Thanks to everyone involved :)
