### ISSUE TITLE
Evaluate status of Assamese (as) locale

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/pm-projects#17]
* [x] Send email to locale leader (Jun 16, 2017)
* [x] Send message to social media
* [x] Drop locale from builds

**Comment by flodolo** [comment]
Received a prompt reply from the former locale leader, who's not active in localization anymore.
The mailing list is empty, no point in sending a message there.

**Comment by flodolo** [comment]
We're going to remove this locale in Firefox 68. The number of users is really limited, might be worth redirecting to en-GB instead of en-US.

**Comment by peiying2** [comment]
For this locale, Mohsin recently joined Pontoon and is very active. He has contributed work for Facebook, Wikimedia and Translators without Borders. I made him a manager at his. I hope he finds friends to collaborate. He has made lots of progress.

**Comment by flodolo** [comment]
That's too late at this point. Firefox remains enabled, if they catch up with localization we can look into re-enable it.

**Comment by peiying2** [comment]
Yeah, I didn't mean to enable it now. Glad he joined us through CV project and is very much interested in beyond the CV projects.
