### ISSUE TITLE
Pre-process terminology list and import

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#171]
**Description:** We need to adjust the formatting of our terminology spreadsheet to facilitate importing the spreadsheet into BWX.

**Stakeholders:**

- [x] Get spreadsheet template from BWX to use a formatting guide.
- [x] Get list of fields and values for terminology entries from BWX.
- [x] Transfer all Firefox terms to new format.
- [x] Test import of newly formatted Firefox terms and note errors/problems.
- [x] Make adjustments to Firefox terms format and re-import (overwrite past import).
- [x] Transfer all Marketing & Advocacy terms to new, tested format.
- [x] Import Marketing & Advocacy terms.

**Comment by gueroJeff** [comment]
Just received the terms template: https://drive.google.com/file/d/1p8BYLzMykSNmNgTCRGpmMApZhlBzOTyy/view?usp=sharing

**Comment by peiying2** [comment]
Using the same set of approved Firefox terms by the terminology team:

1). Firefox Terminology list reviewed by the communities: https://drive.google.com/drive/folders/11m16EEXHHm_xvrQXs4O_Y1l7-ynwErrW It also three list provided by the communities using the same set of approved terms.
2). Firefox Terminology list pulled together by BW by referring to transversion. No review feedback was provided: https://drive.google.com/drive/folders/1Tp8x_MhRcdrAYHGABnvBJaRKSQ13F-ZJ

**Comment by gueroJeff** [comment]
Just created the file with en-US terms, metadata, and all of the terms reviewed by several communities. Challenge now is to determine how to handle multiple entries in a target language for one source language entry (one-to-many).
