### ISSUE TITLE
Create custom TMX from Pontoon

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#177]
We need a custom TMX file for the Thai Firefox project that includes the creationid attribute in each Thai <tuv> element and uses the user name of the localizer as its value (see TMX spec https://www.gala-global.org/tmx-14b#Specs_Attr ).

**Comment by mathjazz** [comment]
Here's the current Thai Firefox TMX file with `creationid` attribute:
https://gist.github.com/mathjazz/63f019409d66e9c75f95b79b98e61c3e

**Comment by gueroJeff** [comment]
Thank you!
