### ISSUE TITLE
Create "untranslatables" term list

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#178]
We need to create an "untranslatables" term list in a consumable format for LexiQA (XLSX, XLS, CSV and tab-delimited TXT files).

**Comment by gueroJeff** [comment]
This appears to be the right starting place: https://www.mozilla.org/en-US/foundation/trademarks/list/

**Comment by gueroJeff** [comment]
After consulting in #terminology on Slack, I took the trademark list and reformatted it as a tab-delimited TXT file.

**Comment by peiying2** [comment]
@gueroJeff There are two parts to this: trademark list and product name list that shouldn't be translated. The 2nd part is hard to confirm, although we have an existing list to work with and fine tune/finalize.

**Comment by gueroJeff** [comment]
@peiying2 I understood my convo with Nathalie in #terminology to mean that the product name list won't be available for this study. If that's not the case, where can I find the product name list in its most recent state? I can incorporate those terms into this .txt file.

**Comment by peiying2** [comment]
https://docs.google.com/spreadsheets/d/1F-n8Wle0BCgim5707kBA74T0eMFnWAsyf0ENJZ04ycg/edit#gid=1612531183 - this is what I have. We probably should start a new file, using this list as a starting point. I am not sure whether all the terms are still in use.

**Comment by gueroJeff** [comment]
There's a solid diff there, thanks for sharing it. I've already created a new .txt file with these terms in it.
