### ISSUE TITLE
Generate Firefox in Italian TMX from Pontoon

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#180]
I need to export the TMX from the Italian/Firefox project in Pontoon.

**Comment by flodolo** [comment]
Zipped TMX

[it.firefox.tmx.zip](https://github.com/mozilla-l10n/pm-projects/files/3447969/it.firefox.tmx.zip)

**Comment by gueroJeff** [comment]
Thanks flod!
