### ISSUE TITLE
Regenerate TMX for both Italian and Thai

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/pm-projects#184]
Unfortunately the first QA reports contain a lot of noise, to the point that it becomes almost impossible to identify real issues among the false positives.

There are a few quick *hacks* to try to minimize the noise in our TMX source.

## Fluent Syntax

Consider the following message:

```properties
addressbar-locbar-bookmarks-option =
    .label = Bookmarks
    .accesskey = k
```

Pontoon's TMX exposes the full syntax:

```XML
<tu tuid="firefox:browserbrowserpreferencespreferencesftl:addressbar-locbar-bookmarks-option" srclang="en-US">
    <tuv xml:lang="en-US">
        <seg>addressbar-locbar-bookmarks-option =
    .label = Bookmarks
    .accesskey = k
        </seg>
    </tuv>
    <tuv xml:lang="it">
        <seg>addressbar-locbar-bookmarks-option =
    .label = segnalibri
    .accesskey = g
        </seg>
    </tuv>
</tu>
```

This causes a ton of errors:
* Punctuation errors, since there's no space between the period and the attribute name
* Spelling errors (attribute names and message ID are in English)
* Accesskey are either reported as inconsistent or identical to source. See following point for that.

Transvision, on the other hand, exports this as two separate strings. The only case where we export syntax is for plurals and functions (e.g. `PLATFORM()`).

```XML
<tu tuid="browser/browser/preferences/preferences.ftl:addressbar-locbar-bookmarks-option.accesskey" srclang="en-US">
    <tuv xml:lang="en-US">
        <seg>k</seg>
    </tuv>
    <tuv xml:lang="it">
        <seg>g</seg>
    </tuv>
</tu>
<tu tuid="browser/browser/preferences/preferences.ftl:addressbar-locbar-bookmarks-option.label" srclang="en-US">
    <tuv xml:lang="en-US">
        <seg>Bookmarks</seg>
    </tuv>
    <tuv xml:lang="it">
        <seg>segnalibri</seg>
    </tuv>
</tu>
```

## Accesskeys and shortcuts

Accesskey are either reported as inconsistent or identical to source. The tool finds `A` for example, and expects all occurrences to be translated in the same way, which is not useful for accesskeys. We should drop them from the TMX for this analysis.

## CSS

CSS rules exposed for localization are often marked as inconsistent translations. There's not much we can do for DTD and properties, but for FTL we should drop the `style` attributes.

**Comment by flodolo** [comment]
Script used is here: https://gist.github.com/flodolo/004c0cf700251b56a642d534314e9ff9

Removed keys:
- Ignored (other products): 18965
- Accesskeys: 1057
- Shortcuts: 127
- CSS style attribute: 39

Both TMX are included in the zip file.

[cleaned_tmx.zip](https://github.com/mozilla-l10n/pm-projects/files/3523712/cleaned_tmx.zip)

**Comment by flodolo** [comment]
Update the Italian TMX, since I've done a few fixes in the meantime

[cleaned_tmx.zip](https://github.com/mozilla-l10n/pm-projects/files/3525306/cleaned_tmx.zip)

**Comment by gueroJeff** [comment]
Thank you for doing this. I've sent the cleaned TMXs to LexiQA.
