### ISSUE TITLE
Ship Catalan Valencia (ca-valencia) in Firefox

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/pm-projects#209]
- [x] File [tracking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=fx-l10n-ca-valencia)
- [x] Set up repositories ([bug 1580090](https://bugzilla.mozilla.org/show_bug.cgi?id=1580090))
- [x] Create Bugzilla component ([bug 1580089](https://bugzilla.mozilla.org/show_bug.cgi?id=1580089))
- [x] Set up productization settings ([bug 1580092](https://bugzilla.mozilla.org/show_bug.cgi?id=1580092))
- [x] Set up Nightly builds ([bug 1580094](https://bugzilla.mozilla.org/show_bug.cgi?id=1580094))
- [x] Test builds
- [x] Add to Beta/Release ([bug 1583171](https://bugzilla.mozilla.org/show_bug.cgi?id=1583171))

**Comment by flodolo** [comment]
Locale is shipping with 71 as of today.

**Comment by gueroJeff** [comment]
Can we close this?

**Comment by flodolo** [comment]
Yup, missed the button when commented on Dec 3.
