### ISSUE TITLE
Create donate repos

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-l10n/pm-projects#219]
I would need to create the following repos under the mozilla-l10n org and become an admin:

`mozilla-donate-content`
`thunderbird-donate-content`

I’ve tried transferring a repo, but GitHub still requires additional permissions.

Those repositories will host Wagtail CMS content for both instances of the new donate stack, and will be set up as additional repos for https://pontoon.mozilla.org/projects/mozilla-donate-website/

Assuming only @flodolo can help with this?

**Comment by flodolo** [comment]
Should be done, double check that you're able to manage settings
https://github.com/mozilla-l10n/mozilla-donate-content
https://github.com/mozilla-l10n/thunderbird-donate-content/

Already added the group for Pontoon.

**Comment by TheoChevalier** [comment]
I am, thanks @flodolo!
