### ISSUE TITLE
Create fomo-l10n repo

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-l10n/pm-projects#227]
Hey flod,

Would you mind creating a `fomo-l10n` repo under the mozilla-l10n org for me please? And make me an admin?
I’m going to migrate this to an external repo https://github.com/mozilla/foundation.mozilla.org/tree/master/network-api/locale

Thanks!

**Comment by flodolo** [comment]
It should be set. Can you confirm you have access?
https://github.com/mozilla-l10n/fomo-l10n/settings/access

Had to figure how the permissions work, they completely changed the UI.

**Comment by TheoChevalier** [comment]
That worked, thanks!
