### ISSUE TITLE
Create donate-l10n repo

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-l10n/pm-projects#228]
Since the string migration went well with `fomo-l10n`, we will do the same for https://github.com/mozilla/donate-wagtail/

@flodolo would you mind creating a `donate-l10n` repo for me please?

Thanks!

**Comment by flodolo** [comment]
Should be done https://github.com/mozilla-l10n/donate-l10n/settings/access

**Comment by TheoChevalier** [comment]
Thanks!
