### ISSUE TITLE
Wrap up BWX

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/pm-projects#231]
[x] User accounts
- [x] Mozilla staff
- [x] Vendor user accounts
- [x] Vendor linguistic user accounts
- [x] Jeff's and Pei's accounts

[x]Connectors
- [x] Github to www-l10n - Pike
- [x] SurveyGizmo - [bug 1624069](https://bugzilla.mozilla.org/show_bug.cgi?id=1624069)
- [x] [Google Play](https://bugzilla.mozilla.org/show_bug.cgi?id=1575603) - email sent (Julien)
- [x] [App Store](https://bugzilla.mozilla.org/show_bug.cgi?id=1575607) - email sent (AtLee)
- [x] Google Team Drive - removed users

[x] Export
- [x] [TM](https://drive.google.com/drive/folders/1Mx3pQKGDo5mTKcLJGogE_hCYHaKN2YDi)
- [x] [Terminology](https://drive.google.com/drive/folders/1qbrOBvuZb41mTezk1CA9xlJZqqxKQdBi)

[x] Communication: Slack channel

[x] Invoice (Marcio)

**Comment by gueroJeff** [comment]
As of April 6th, I'm still able to log into Bureau Works.

**Comment by peiying2** [comment]
All the tasks have completed.
