### ISSUE TITLE
Create a snapshot of data for projects clean up

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/pm-projects#235]
For #232 

- [x] Get the list of Firefox locales
- [x] Check the data available in Pontoon's API: number of projects, missing strings, pending suggestions, latest activity (likely not available).
- [x] Write script to extract data in CSV format
- [ ] Create spreadsheet with data

**Comment by flodolo** [comment]
I still need to start working on this, but we need to cut the data close to sending the emails. When are we planning to do that?

**Comment by flodolo** [comment]
List of Firefox locales (96)

```
firefox_locales = [
    'ach', 'af', 'an', 'ar', 'ast', 'az', 'be', 'bg', 'bn', 'br', 'bs', 'ca',
    'ca-valencia', 'cak', 'cs', 'cy', 'da', 'de', 'dsb', 'el', 'en-CA',
    'en-GB', 'en-US', 'eo', 'es-AR', 'es-CL', 'es-ES', 'es-MX', 'et', 'eu',
    'fa', 'ff', 'fi', 'fr', 'fy-NL', 'ga-IE', 'gd', 'gl', 'gn', 'gu-IN', 'he',
    'hi-IN', 'hr', 'hsb', 'hu', 'hy-AM', 'ia', 'id', 'is', 'it', 'ja', 'ka',
    'kab', 'kk', 'km', 'kn', 'ko', 'lij', 'lt', 'lv', 'mk', 'mr', 'ms', 'my',
    'nb-NO', 'ne-NP', 'nl', 'nn-NO', 'oc', 'pa-IN', 'pl', 'pt-BR', 'pt-PT',
    'rm', 'ro', 'ru', 'si', 'sk', 'sl', 'son', 'sq', 'sr', 'sv-SE', 'ta', 'te',
    'th', 'tl', 'tr', 'trs', 'uk', 'ur', 'uz', 'vi', 'xh', 'zh-CN', 'zh-TW',
]
```

**Comment by flodolo** [comment]
Latest activity can be scraped from the [Teams page](https://pontoon.mozilla.org/teams/)
https://gist.github.com/flodolo/bd93a8f146668ed58f74b318b820a4d6

**Comment by flodolo** [comment]
Script to extract data from Pontoon API, need to be manually integrated with last activity in the spreadsheet
https://github.com/flodolo/scripts/blob/master/pontoon_api/extract_locales_data.py

**Comment by flodolo** [comment]
## Data about Projects

Pending suggestions, number of projects, etc. via API
https://docs.google.com/spreadsheets/d/1OH5VKmdNMYX-gn5W0QSeeQ8C2oazqNrf7iag2htBNP8/edit#gid=0

Cut off for Pontoon data (projects): May 27, 8:20 UTC

## Full analysis

Managers, contributors, etc.
https://docs.google.com/spreadsheets/d/1v5Guzcwzip1bCtzd1K4tfqbVPzv7EmmJk4iENWuAi9k/edit#gid=1448748328

Notes:
* Some data is based on the last year (May 27 2019 - May 27 2020): active reviewers, self approval, suggestions lifespan.

*IMPORTANT*: make a copy of the spreadsheet if you want to make changes, it's a lot of formulas and logic that can break easily.

Both documents are in this folder
https://drive.google.com/drive/u/0/folders/1eE3WEzPTjS-TnacyulM17zFdFqsF-ZC2

**Comment by gueroJeff** [comment]
Thank you!
