### ISSUE TITLE
Create Smartling template for snippets

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#243]
Create a standard template for translating snippet content through Smartling. Template must be a .csv file with the appropriate Smartling directives. Template must be discoverable to marketing teams.

The following specifications must be met for a snippet content template:

**Comment by peiying2** [comment]
Templates and examples for [Snippets](https://drive.google.com/drive/folders/1bcoc_R8F2tCmAgpKJN2QJUNJ7VC5aSnI) request:
- [x] Instruction and process for requester and copy preparer.
- [x] Email copy template with directives in spreadsheet
- [x] Export of the template in .csv
- [x] Example of localized file downloaded from Smartling
- [x] Example of localized file delivered to customer.

**Comment by peiying2** [comment]
@gueroJeff please review when you get a chance.
