### ISSUE TITLE
Create Smartling template for email content

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#244]
Create a standard template for translating email content through Smartling. Template must be a .csv file with the appropriate Smartling directives. Template must be discoverable to marketing teams.

The following specifications must be met for an email content template:

**Comment by peiying2** [comment]
Templates and examples for [Email](https://drive.google.com/drive/folders/1B8ZQGbjD1Gm-K2J928z-xO57YLn90nxC) request:
[x] Instruction and process for requester and copy preparer.
[x] Email copy template with directives in spreadsheet
[x] Export of the template in .csv
[x] Example of localized file downloaded from Smartling
[x] Example of localized file delivered to customer.

**Comment by peiying2** [comment]
@gueroJeff please review when you get a chance.
