### ISSUE TITLE
Create Smartling template for blog posts

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#245]
Create a standard template for translating blog post content through Smartling. Template must be a .xliff file with the appropriate Smartling directives. Template must be discoverable to marketing teams.

The following specifications must be met for a blog post content template:

**Comment by peiying2** [comment]
@gueroJeff here is a blog file example:  https://drive.google.com/file/d/1YvxsK4ELVUSiDf-_3DuvKoafXunhlQ4t/view?usp=sharing. Note, each blog file is locale specific due to the way it was exported.

**Comment by gueroJeff** [comment]
There are limited (maybe 5) directives for XLIFF files, and the one that matters to us is not a document level directive, but a trans-unit level directive. Meaning, before the XLIFF gets imported to Smartling, it needs a pre-processing step that inserts the directive before every trans-unit tag. For now, that will just need to be a manual process, and automating it will require writing and running a python script that insert those directives in the right place. 

I mention this because the number of directives will vary based on the number of trans-unit elements in the document. There’s no template that we can create that can function similar to the csv-based content types. So instead, I made some significant changes to the process spreadsheet to reflect the manual directive insertions that will need to take place each time, and added the import and export files to the directories, as points of reference. 

The good news, however, is that with the directives being HTML compliant, we don't have to strip them in a post-processing step. This was verified with Craig.

All this being said, the process document is ready for your review @peiying2 https://drive.google.com/drive/folders/1HgTesbsdUGc0HNEQm0Fmc5vpcB5SRpDX
