### ISSUE TITLE
Define Smartling directives for mozorg files

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#247]
Define appropriate Smartling directives for mozorg .ftl files.

**Comment by peiying2** [comment]
Update: code is on production and the round trip testing looks good: https://github.com/mozilla-l10n/tooling_test_repo/tree/main/www-l10n-test/sl-test.

Sergio also said, the current flow supports Fluent fully, therefore, no need for directives for mozorg workflow. If we have third party references in the flow in the future, we have to have customized directives for that. So technically, we can mark this one as complete.

**Comment by gueroJeff** [comment]
Closing per Peiying's comment.
