### ISSUE TITLE
Create Smartling template for legal docs

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#248]
Create a standard template for translating legal doc content through Smartling. Template must be a .md file with the appropriate Smartling directives. Template must be discoverable to legal teams.

The following specifications must be met for a legal content template.

Dependency of https://github.com/mozilla-l10n/pm-projects/issues/241

**Comment by peiying2** [comment]
There are two types of Legal doc requests:
- Automated through connector with Legal doc repo 
- Manual if the doc is a single file, for internal use or for breach alert. It has always been a single language file, and it is in Word.

**Comment by peiying2** [comment]
@gueroJeff please +r

**Comment by gueroJeff** [comment]
r+
