### ISSUE TITLE
Update Firefox Android (Fenix) work to "sat" on Pontoon

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#253]
- [x] Temporarily disable sync for project in Pontoon
- [x]  Edit locale in pontoon.mozilla.org/a/ -> rename "sat-Olck" to "sat"
- [x] Update both A-C and Fenix l10n.toml files with "sat" locale
- [x] Rename repo folder name to "sat" for [Fenix here](https://github.com/mozilla-l10n/android-l10n/tree/master/mozilla-mobile/fenix/app/src/main/res)
- [x] Rename all files that **[A-C repo contains](https://github.com/mozilla-l10n/android-l10n/tree/master/mozilla-mobile/android-components/components/browser)** (vs Fenix, there are multiple files there)
- [x] Merge PR containing all the above
- [x] Re-enable sync
- [x] Communicate to mobile team about this, so they are aware

**Comment by Delphine** [comment]
@flodolo @mathjazz : Do the steps here seems in the right order? Am I forgetting to list any steps?
thanks!

**Comment by flodolo** [comment]
I think you should rename the folder in the repo when you update the toml files? Not exactly sure if that will mess up with automation :-( 

What I would do is:
* Create *sat* locale in Pontoon, set up permissions
* Temporarily stop sync for the project
* Have Matjaz migrate the project to *sat*
* Make changes to the repository (while sync is still disabled)
* Re-enable sync

This applies also to Firefox for iOS, with the advantage that there's no automation to mess up with and it's safe to do.

**Comment by Delphine** [comment]
Note: comment above is obsolete since I had to work another way on this project

**Comment by Delphine** [comment]
This has been fixed via https://github.com/mozilla-l10n/android-l10n/pull/286
