### ISSUE TITLE
Update Terminology work to "sat" on Pontoon

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#254]
EDIT: nothing to do here, since Terminology doesn't have a repo

**Comment by Delphine** [comment]
@flodolo @mathjazz: Seems like I forgot that there was Terminology there as well 🙄
Are the steps basically the same for this project as well? For example, I don't think "make changes to the repo" applies here, but also want to make extra sure. Thank you both!

**Comment by flodolo** [comment]
Terminology doesn't have a repository, so it's all on Matjaz.
