### ISSUE TITLE
Create Smartling template for survey content 

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/pm-projects#256]
Create a standard template for translating email content through Smartling. Template must be a .csv file with the appropriate Smartling directives. Template must be discoverable to marketing teams.

The following specifications must be met for an email content template:

Templates and examples for [Survey](https://drive.google.com/drive/folders/19YNmvp00ANchjD5T8uaxQlypiOSiePsn) request:
- [x] Instruction and process for requester and copy preparer.
- [x] Email copy template with directives in spreadsheet
- [x] Export of the template in .csv
- [x] Example of localized file downloaded from Smartling
- [x] Example of localized file delivered to customer.

**Comment by gueroJeff** [comment]
I left a couple of comments, but I'm going to close this out. It all looks good and the directives look well formed.
