### ISSUE TITLE
KR2: 85% of the top 20 locales attend any of 3 virtual training workshops

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#262]
- [ ] Compile the list of managers and translators interested in becoming managers
- [ ] Split locales by timezone
- [ ] Decide when workshops will take place, and which drivers should participate
- [ ] Create content needed for workshop
- [ ] Send invitations

**Comment by peiying2** [comment]
Is `Create content needed for workshop` already covered in the list of KR1

If there  is anything to add, maybe a list of people attended the event, so we can see if 85%+ did?

**Comment by flodolo** [comment]
I think all of these belong to KR1. For KR2, we only need to keep track of the attendants, and see if we met the goal.
