### ISSUE TITLE
Add config to mozorg repo

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#265]
Need to do the following to config files:
- [x] Create [.json config](https://help.smartling.com/hc/en-us/articles/360008154073-Repository-Connector-Translation-Settings), specifying ms first
- [x] Remove ms from pontoon.toml
- [x] Ensure smartling.conf file points to transaltion .json config file in mozorg repo.

**Comment by peiying2** [comment]
@gueroJeff Please review the PR: https://github.com/mozilla-l10n/www-l10n/pull/176 
- please confirm if we are still aiming at `ms` first or we will go with 5 locales. I can update accordingly..
