### ISSUE TITLE
Set up context capture automation

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#266]
Mozorg translators need the in-context editor to perform high-quality localization. Manually, this can be a very tedious process. We need to set up automation to run context capturing with each new job added to the mozorg Smartling project.

[The process steps and validation info is here](https://help.smartling.com/hc/en-us/articles/360007995793-Smartling-s-Context-Capture-Chrome-Extension).

**Comment by gueroJeff** [comment]
Context capture automation created with mozilla project UID and custom site map from the Bedrock team (@peiying2 could you put that in Google Drive and share the link here please?)

**Comment by peiying2** [comment]
The file can be found [here](https://drive.google.com/drive/u/0/folders/1YNUzU3mMa4zMAfJFPN1Z7PS_cswzu9Qa)
