### ISSUE TITLE
Set up site analytics dashboards to capture bet data

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#268]
We need dashboards that visualize site analytics pertaining to this bet. Specifically, we need to be able to visualize current and historic data on active sessions, conversion rate (downloads), and Firefox new profiles for the following language codes and the following countries.

Languages:
- ar
- hi-IN
- id
- ja
- ms

Countries:
- Egypt
- Algeria
- Saudi Arabia
- Jordan
- Tunisia
- India
- Indonesia
- Japan
- Malaysia
- Singapore

**Comment by flodolo** [comment]
Active sessions: you mean sessions on mozilla.org?

I think I can help with the new profiles data. From what I've seen, we can track down the country, still not sure about locale though.

**Comment by gueroJeff** [comment]
Yes, sessions on mozilla.org.

Sessions and conversion rate (downloads) should come from mozorg, the new
profiles data would come from a different source (telemetry?). I expect we
can synchronize that data and create dashboards in telemetry utilizing both
sources. Is that assumption false?

**Comment by flodolo** [comment]
We can create a dashboard from multiple queries:
- The data about new profiles is available in telemetry
- I've seen the query you have for downloads on mozilla.org, and I should be able to adapt it
- I have no clue about sessions, for that we should ask mozilla.org folks (or who gave you the download query?)

**Comment by flodolo** [comment]
Tracking the new profiles part in https://github.com/mozilla-l10n/pm-projects/issues/271

**Comment by flodolo** [comment]
Started a [dashboard here](https://sql.telemetry.mozilla.org/dashboard/l10n---mozilla-org-funnel-beta-2021-h1-), more details in the issue above.

**Comment by flodolo** [comment]
I plan to take a look at mozilla.org after this (found the [definition of the table](https://github.com/mozilla/bigquery-etl/tree/master/sql/moz-fx-data-marketing-prod/ga_derived/www_site_metrics_summary_v1)).

**Comment by flodolo** [comment]
I've added downloads and sessions per country and locale in https://github.com/mozilla-l10n/pm-projects/issues/272 

@gueroJeff How do you define *conversion rate*?

**Comment by gueroJeff** [comment]
> I've added downloads and sessions per country and locale in #272
> 
Thank you!
> @gueroJeff How do you define _conversion rate_?
I'm defining this as the rate active sessions converting to downloads. Comparing downloads against active sessions though, may give us that rate.

**Comment by flodolo** [comment]
Update with a conversion rate field (nr downloads/nr sessions). Also filtered the query per country to only look at the 5 locales, since they don't overlap geographically and we want to ignore other locales.
