### ISSUE TITLE
Create mozorg project in Smartling

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#270]
Using the following requirements:
- [ ]Repo connector
- [ ]ar, hi-IN, id, ja, ms funneled to Mother Tongue
- [ ]de funneled to Anika
- [ ]Context capture configured to project
- [ ]Using unified language resource package.
- [ ]cron set up to pull/push daily

**Comment by peiying2** [comment]
@gueroJeff I have created the mozorg project [here](https://dashboard.smartling.com/app/projects/4fc3ceb0b/project-dashboard/index.html). 
- All languages are funneled to Mother Tongue except for de/fr. *All* means not just limited to the 5 we are focusing on. The control of the 5 languages will be from the config .toml files. Let me know if this is not the case and I can remove the non-relevant languages. 
- de and fr are funneled to staff. I will send an email on the resource issue. We can remove fr if no short term resolution.

**Comment by peiying2** [comment]
mozorg sitemap (for context capture purpose): https://www.mozilla.org/en-US/sitemap.xml. Do we need locale specific xml file?

**Comment by gueroJeff** [comment]
> mozorg sitemap (for context capture purpose): https://www.mozilla.org/en-US/sitemap.xml. Do we need locale specific xml file?

No, we only need the general sitemap.

**Comment by peiying2** [comment]
The US site map consists more than 2700 links. The decision is to use `de` sitemap as it contains the most of localized pages:
- change `de` to `en-US`
- change prod URL to dev URL.
