### ISSUE TITLE
Create content needed for workshops

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#277]
- [ ] Slides
- [ ] Gear

**Comment by flodolo** [comment]
Didn't we drop "gear" at this point? I also don't think that counts as content.

**Comment by peiying2** [comment]
We need to ask what Jeff wants to do with Gear, a dependency on him to set it up if we need it. I remember it's a matter of bandwidth to have it ready. But also agree on this not being part of the content category. We can sort it out, to remove or add a new issue.

**Comment by Delphine** [comment]
Flagging @gueroJeff when he's back so he can give an update on the gear :)

**Comment by Delphine** [comment]
This should be done by May 27th

**Comment by Delphine** [comment]
Gear won't be possible unfortunately.
We may or may not want to have slides for this, I see both working out.

@peiying2 What do you think about having slides? and if so, for what kind of content?
The calls will be more an active discussion / breakout sessions - so perhaps it doesn't make a lot of sense to have them?

**Comment by peiying2** [comment]
> @peiying2 What do you think about having slides? and if so, for what kind of content?
> The calls will be more an active discussion and breakout sessions - so perhaps it doesn't make a lot of sense to have them?
If we have a slide, have a page on the agenda for the meetup so it looks like we have a plan/structure. It is less about presentation but more on what we are going to cover during the meetup. Between the two of us, we can have some idea on how much time we want to spend on each session but stay fluid and modify based on the actual situation.

**Comment by peiying2** [comment]
> > @peiying2 What do you think about having slides? and if so, for what kind of content?
> > The calls will be more an active discussion and breakout sessions - so perhaps it doesn't make a lot of sense to have them?

If we have a slide, have a page on the agenda for the meetup so it looks like we have a plan/structure. It is less about presentation but more on what we are going to cover during the meetup. Between the two of us, we can have some idea on how much time we want to spend on each session but stay fluid and modify based on the actual situation.
