### ISSUE TITLE
Create a doodle poll for Asia

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#289]

**Comment by gueroJeff** [comment]
Looking for feedback: https://doodle.com/poll/xne38rmam895946m @Delphine @peiying2

**Comment by peiying2** [comment]
> Looking for feedback: https://doodle.com/poll/xne38rmam895946m @Delphine @peiying2

Looks good. You can mention that once the meeting times are set, invitation with more detailed agenda will be shared and the virtual meeting will be held on Zoom.

**Comment by Delphine** [comment]
LGTM. Agreed with Peiying. 
In follow-up emails, we can also ask pzrticipants to read the last ten (or so) l10n reports.
