### ISSUE TITLE
Ship Santali (sat) in Firefox

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/pm-projects#302]
- [x] File [tracking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=fx-l10n-sat-2021)
- [x] Set up Nightly builds ([bug 1731528](https://bugzilla.mozilla.org/show_bug.cgi?id=1731528))
- [x] Set up productization settings
- [x] Verify localization progress over at least 2 cycles
- [x] Verify number of users on the Nightly channel
- [x] Test builds
- [x] Set up language names ([bug 1852843](https://bugzilla.mozilla.org/show_bug.cgi?id=1852843))
- [x] Add to Beta/Release ([bug 1853054](https://bugzilla.mozilla.org/show_bug.cgi?id=1853054))
- [x] Update language pack metadata
- [x] Fix native locale name on addons.mozilla.org ([PR](https://github.com/mozilla/addons-frontend/pull/12429))

**Comment by bcolsson** [comment]
Bug to set up language names for Santali (sat)
https://bugzilla.mozilla.org/show_bug.cgi?id=1852843

Productization settings step skipped (left same as en-US) to expedite addition to Beta/Release

**Comment by flodolo** [comment]
I'm going to take care of updating https://github.com/mozilla-l10n/firefox-languages, because I need to add some basic instructions to the README first.

**Comment by flodolo** [comment]
> I'm going to take care of updating https://github.com/mozilla-l10n/firefox-languages, because I need to add some basic instructions to the README first.

This is done (added info to README, updated packages, and cleaned up some scripts)
https://github.com/mozilla-l10n/firefox-languages/commits/main

**Comment by bcolsson** [comment]
Thanks for taking care of the above, I wasn't aware of the need to do this (didn't see this repo mentioned in the [Beta/Release build](https://mozilla-l10n.github.io/documentation/products/firefox_desktop/adding_release.html#add-locale-to-build-configuration) documentation. Should we add this?

Bug/patch created for adding to build system: https://bugzilla.mozilla.org/show_bug.cgi?id=1853054

**Comment by flodolo** [comment]
> Thanks for taking care of the above, I wasn't aware of the need to do this (didn't see this repo mentioned in the [Beta/Release build](https://mozilla-l10n.github.io/documentation/products/firefox_desktop/adding_release.html#add-locale-to-build-configuration) documentation. Should we add this?

It is [here](https://mozilla-l10n.github.io/documentation/products/firefox_desktop/adding_release.html#verify-language-name)

> Add the localized language name in the nativeLocaleNames [map](https://searchfox.org/mozilla-central/rev/b3933df6e119bd6caf5d9e5868670348ec26dee3/toolkit/components/mozintl/mozIntl.jsm#650). The localized language name should also be stored in [this repository](https://github.com/mozilla-l10n/firefox-languages/blob/master/output/languages_curated.json).

> Bug/patch created for adding to build system: https://bugzilla.mozilla.org/show_bug.cgi?id=1853054

Note: add the link to the first post, so they're easier to find.

**Comment by bcolsson** [comment]
The Santali locale was already enabled in langpacks so you can already download Beta in Santali, and enable Santali from the language checker. I've created on [PR](https://github.com/mozilla/addons-frontend/pull/12429) for addons because the display name needs to be updated [here](https://addons.mozilla.org/en-US/firefox/language-tools/) (it's using the incorrect script).

**Comment by flodolo** [comment]
> I've created on [PR](https://github.com/mozilla/addons-frontend/pull/12429) for addons because the display name needs to be updated [here](https://addons.mozilla.org/en-US/firefox/language-tools/) (it's using the incorrect script).

Make sure you add things to action items in the first post, so it's easier to track completion and work.

**Comment by flodolo** [comment]
> The Santali locale was already enabled in langpacks so you can already download Beta in Santali, and enable Santali from the language checker.

Can you clarify this? Have you reached out to AMO admins to confirm the metadata?

**Comment by bcolsson** [comment]
Reread through my notes and realized it wasn't just an issue of getting the language pack to appear. Reached out to AMO and waiting for a response. (Reading the documentation I came to the erroneous conclusion that as long as it was showing up then everything needed to be done was done.)
