### ISSUE TITLE
Create message to send out with pre-survey

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#304]
Create a small email explaining where this survey idea comes from, why we are doing this, how much time it takes to complete, etc. So, just giving some basic context.

Section for email is at the end of this doc: https://docs.google.com/document/d/1rzgaHQn2__QYFThjJYhCsIEpFfHbOJUnjwbjfeOgll8/edit#heading=h.g3312yzuivr
("Message to send out with survey")

**Comment by Delphine** [comment]
Deadline: ready by Monday Nov 15, morning Pacific Time

**Comment by peiying2** [comment]
@Delphine when you get a chance, please have a look.

**Comment by Delphine** [comment]
Review done by Flod and me. Thanks! Closing this.
