### ISSUE TITLE
Compile the list of localizers we will invite

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#316]

**Comment by flodolo** [comment]
Notes:
* Script to extract locales [here](https://gist.github.com/flodolo/e157bf85dec9697ed8ffbc0a3fa1f615)
* Script to extract starts from Pontoon [here](https://github.com/flodolo/scripts/blob/master/pontoon/active_contributors.py)

Right now, we would have 154 locales, 891 active contributors (contributors, managers, translators).

By filtering with at least 50 approved translations, we get down to 198 recipients. By increasing the limit to 100, we have 157 recipient.

Document available [here](https://docs.google.com/spreadsheets/d/1Yq1-EMpRNYLuDBKveU3DO7TY409p2-CWTaP9XxuoYdo/edit#gid=1571018629).

**Comment by Delphine** [comment]
Wow - that's a lot of folks.
Having said that, given the experience with workshops last year, better to invite more than less.
How about sticking with the 50 approved translations?

**Comment by flodolo** [comment]
> How about sticking with the 50 approved translations?

Sounds good to me. Note that we'll need to look at the number again, depending on when we send out invitations.

**Comment by flodolo** [comment]
Added sheet with updated list. With ≥ 100 translations, we get 189 people. With  ≥50, it's 235 people.

**Comment by flodolo** [comment]
I just realized the script returns duplicate values (randomly spotted a contributor in German with more than 1k strings, it was Théo).

871 contributors is actually 580 without duplicates. So, 187 becomes 175, which still seems enough.

@mathjazz will need to filter out duplicates when sending emails.

**Comment by flodolo** [comment]
One more correction (I was looking at translation instead of approved):
* Total contributors (with duplicates): 871
* Total unique contributors: 580
* Unique users with ≥ 100 approved translations: 146
* Unique users with ≥ 50 approved translations: 175

The spreadsheet is currently filtered on ≥ 50
