### ISSUE TITLE
Assign timeslots for presentations

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/pm-projects#323]
@flodolo @peiying2: this is one of our next steps now. 
How about we brainstorm around this, early during the workweek?

**Comment by peiying2** [comment]
Yes, let's do that. Faster in person.

**Comment by Delphine** [comment]
(Note: general moderator to be Amir)

    General introductions of l10n-drivers (moderator: delphine) - 15 min
    What’s new in Mozilla l10n - High Level (delphine) -10 min
    State of mobile (delphine) - 5 min
    Firefox Relay (Peiying) -5 min
    Mozilla.org: common issues, what to watch out for, and outstanding issues that are pending review and fixes (Peiying)
    Part 1: Recent and less popular features in Pontoon (Matjaz)
    Part 2: UI Pontoon new and upcoming features, with a live demo (Matjaz)
    Feedback session to collect pain points and ideas (Matjaz)
    Workflows: reviewing each other suggestions, style guides, comments, TM, etc (flod)
    How to increase the number of contributors.
    How to become a manager and how to manage your community (Peiying and a localizer TBD)
    How to better interact with members of your locale - let's see if we pick this or not
    Testing commercial products - le'ts see if we pick this or not

**Comment by Delphine** [comment]
Given the change in participants (me and Eemeli), we should reconsider the topics we want to cover in 2 hours.

**Comment by Delphine** [comment]
Latest sessions we chose: 
(general moderator  note taker = Amir)
General introductions of l10n-drivers (moderator: delphine) - 10 min
What’s new in Mozilla l10n - High Level (delphine) - 10 min
State of mobile (delphine) - 10 min
Firefox Relay (Peiying) -10 min
Mozilla.org: common issues, what to watch out for, and outstanding issues that are pending review and fixes (Peiying) -10 min
Part 1: Recent and less popular features in Pontoon (Matjaz) -10 min
Part 2: UI Pontoon new and upcoming features, with a live demo (Matjaz) - 10 min
Feedback session to collect pain points and ideas (Matjaz) - 10 min
Workflows: reviewing each other suggestions, style guides, comments, TM, etc (flod) 20 min
Q&A: 15 min

That's about 2hours, if I'm not mistaken

**Comment by bcolsson** [comment]
Following up on our conversation @Delphine - I wanted to add a quick primer (shoot for 5 minutes) on Firefox Accounts

**Comment by mathjazz** [comment]
> * Part 1: Recent and less popular features in Pontoon (Matjaz) -10 min
> * Part 2: UI Pontoon new and upcoming features, with a live demo (Matjaz) - 10 min
> * Feedback session to collect pain points and ideas (Matjaz) - 10 min

Can I join these 3 session into a single Pontoon session, called something like "Pontoon: new features and ideas".

I'd start with an overview of more recently released and soon-to-be added features. Then I'd hand over the microphone to localizers and listen to their ideas for improvements.

**Comment by Delphine** [comment]
@mathjazz That sounds great to me. I will update the agenda with this, and send a follow up email soon to invitees so they can already start thinking about ideas. thanks!

**Comment by mathjazz** [comment]
Thanks! I've removed the Part 1-3 bullet points, because I think they aren't necessary, perhaps even a bit confusing.
