### ISSUE TITLE
Barcelona Goals and Agenda

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#33]
# Core focus:
- Rebuilding communities
- Evangelizing localized products
- Quality
- Training on tooling changes

# Outcomes:
- Localizers can recruit and train new localizers.
- Each community's language resources (style guides, term lists) are created & up-to-date.
- Marked improvement in localization quality for l10n projects.
- Localizers trained in translation process best practices.

# Format:
## Day 1:
**Morning**
- Spectograms
- Org updates

**Afternoon**
- Common goals breakouts
- Free time (goals work, 1:1 time with l10n-drivers, community visits with l10n-drivers)
## Day 2:
- Common goals breakouts
- Free time (goals work, 1:1 time with l10n-drivers, community visits with l10n-drivers)

# Planning:
The l10n-drivers will coordinate among l10n communities to identify common goals and split up time into breakout sessions. Otherwise, we will only need a few hours in the first morning to accomplish our own goals (give Mozilla org updates, roadmap updates, l10n program updates, etc.). 

The content and goals for the afternoons and the second morning are entirely open for the communities to fill with what they feel is most worthy of their time. Here are some questions that can help guide defining what this time could be filled with:
- What does the l10n community hope to accomplish during the hackathon?
- Are open, group discussions more valuable or are breakouts more valuable?
- Would there be value in holding an open public time during the hackathon?
- What does the l10n community hope to bring back to their larger community?

**Comment by gueroJeff** [comment]
Wiki event page created: https://wiki.mozilla.org/L10n:Meetings/2017_Barcelona_Workshop

Please begin planning goals and agenda.

**Comment by kberov** [comment]
Hello @gueroJeff ,
Are we expected to add to the [wiki page](https://wiki.mozilla.org/L10n:Meetings/2017_Barcelona_Workshop) what we think needs to be done on the workshop for the respective localization community?

**Comment by Facyber** [comment]
Goals for my (Serbian) community are:

- New Style Guide (editing Wiki page and creating docx and pdf format of a guide)
- Finishing not translated projects on Pontoon (Mozilla.org > Firefox Accounts > Appstores, sorted by priorities)
- If we manage to finish all this before the end of event, we will continue with translation of Lightning Aurora. As there are a lot of untranslated strings, we will translate as many as we can.

**Comment by gueroJeff** [comment]
@kberov Commenting in this issue is enough. It makes an open discussion about these easy to manage.

**Comment by kberov** [comment]
@gueroJeff  Thanks!

**Comment by gocemitevski** [comment]
Goals for the Macedonian community:

* Create a Style Guide
* Make substantial progress with the localization of Firefox Aurora -- try to reach at least 80% completeness
* Figure out how to rebuild our community

**Comment by gastaz** [comment]
Goals for the Ligurian (lij) community:
- Reach the 100% of completion of Firefox Aurora (now is 96%)
- Find new volunteers for ligurian localization
- Decide if add new projects for ligurian
- Create style guide

**Comment by gion-andri** [comment]
The goals for the Romansh (rm) community: 
- Clean up our terminology list, make it more structured
- Make sure, all suggested translations are reviewed
- Complete translation of Firefox Aurora (currently at 95%)
- Discuss, how we could modify our team’s translation process to avoid suggestions not going into the product if nobody has time for the review

**Comment by HrantOhanyan** [comment]
Goals for the Armenian community:

- Update the Style Guide.
- Make a decision to add new projects for localization.
- Review existing suggestions in all platforms.
- Translate missing strings in Firefox, Firefox for Android and Thunderbird.

**Comment by cristisilaghi** [comment]
Goals for the Romanian community:
- Update the style guide
- Complete Focus for iOS, Firefox for iOS, Firefox Accounts projects
- Translate and/or update top 10 articles from SUMO
- Discuss about the state of the community and how to find new localizers for Romanian locale

**Comment by cristisilaghi** [comment]
Goals for the Romanian community:
- Update the style guide
- Complete Focus for iOS, Firefox for iOS, Firefox Accounts projects
- Translate and/or update top 10 articles from SUMO
- Discuss about the state of the community and how to find new localizers for Romanian locale

_Off-topic: @gueroJeff little typo on wiki page: EUR is used in Barcelona, not INR :)_

**Comment by julen** [comment]
As for Basque:
* Research on deploying [a solution for gathering TM and terminology](https://github.com/Softcatala/translation-memory-tools) (not limited to Mozilla)

**Comment by meskobalazs** [comment]
Goals for the Hungarian team:

- Update our existing, but outdated style guide
- Discuss the revival of our glossary
- Make a strategy for MDN translation (decide what to translate, and what not; involvement of new translators)
- Compile the list of features needed in Pontoon, to allow the migration of all projects from Pootle
- Discuss the state of the local community

**Comment by AndreiTarkovski** [comment]
Goals for Slovenian team:

- Enhance glossary
- Define ways to expand localisation community
- Build 1-stop-point for all useful linguistic resources
- Reach 100 % progress

**Comment by jlgl10nes** [comment]
Goals for the Spanish team

- Discuss about the state of the community, find and support new contributors (es-ES and es)
- Documentation review and update (wiki, style guide, glossary)
- Tools and project request criteria

**Comment by goofy-bz** [comment]
Goals for French team:

- Start a usable guide in French for newcomers on the new not-so-localizer-friendly SUMO platform :smile: 
- Prepare material and docs in order to welcome high-level translators we invited for their first contribution on Mozilla on April 8-9th in Paris.  It includes conf to introduce  them to various l10n tasks, tools and process, and also find a range of activities to be proposed during the week-end (docs, pages, tech/non-tech articles)
- Review and validation of the pending suggestions on Pontoon.
