### ISSUE TITLE
Pick 10 features for the 2024 Pontoon survey

### ISSUE THREAD

**Issue by mathjazz** [mozilla-l10n/pm-projects#352]
We need to select 10 features for the community to vote on in the 2024 Pontoon survey. 
We'll commit to implementing the 3 top-voted features in 2024.

Here's my proposed list:

1. https://github.com/mozilla/pontoon/issues/2059 [(2022 runner-up)](https://github.com/mozilla/pontoon/issues/2355)
1. https://github.com/mozilla/pontoon/issues/2255 [(2022 runner-up)](https://github.com/mozilla/pontoon/issues/2355)
1. https://github.com/mozilla/pontoon/issues/2276 [(2022 runner-up)](https://github.com/mozilla/pontoon/issues/2355)
1. https://github.com/mozilla/pontoon/issues/3031
1. https://github.com/mozilla/pontoon/issues/3032
1. https://github.com/mozilla/pontoon/issues/2232
1. https://github.com/mozilla/pontoon/issues/2076
 (was: ~https://github.com/mozilla/pontoon/issues/2790~)
1. https://github.com/mozilla/pontoon/issues/2310
1. https://github.com/mozilla/pontoon/issues/2108
1. https://github.com/mozilla/pontoon/issues/2138

Please let me know if we should remove some of the items and provide a replacement in the comments below.

**UPDATE 22/11/23:** I've added [Bryan's idea](https://github.com/mozilla-l10n/pm-projects/issues/352#issuecomment-1817246000) and removed one as [suggested by Flod](https://github.com/mozilla-l10n/pm-projects/issues/352#issuecomment-1817465118).

**Comment by bcolsson** [comment]
One more to consider to gauge whether active contributors are interested in receiving emails from Pontoon:
-  https://github.com/mozilla/pontoon/issues/2076

**Comment by flodolo** [comment]
I have some concerns about 6. There are so many variables there (e.g. we don't want someone to pretranslate 2k strings in a project, and that's why we evaluate each request to enable pretranslation), also given we're still seeing a good amount of tiny errors.

**Comment by Delphine** [comment]
Agreed with Bryan on adding https://github.com/mozilla/pontoon/issues/2076.
Otherwise list LGTM

**Comment by peiying2** [comment]
> I have some concerns about 6. There are so many variables there (e.g. we don't want someone to pretranslate 2k strings in a project, and that's why we evaluate each request to enable pretranslation), also given we're still seeing a good amount of tiny errors.

For web based projects, an in-context page would be nice. mozilla.org is known for containing long and complicated strings. It's beneficial to have it available. I assume this one is for all projects using Fluent.

**Comment by peiying2** [comment]
Numbers: 3, 4, 11 (Bryan's)

**Comment by bcolsson** [comment]
> Nos: 3, 4, 11 (Bryan's)

Is this Nos as in "Numbers" or "Nos" (as in Yeses and Nos)?

**Comment by peiying2** [comment]
> > Nos: 3, 4, 11 (Bryan's)
> 
> Is this Nos as in "Numbers" or "Nos" (as in Yeses and Nos)?

Numbers. When I typed # it points to some issues, :).  Updated to avoid confusion.

**Comment by mathjazz** [comment]
> I have some concerns about 6. There are so many variables there (e.g. we don't want someone to pretranslate 2k strings in a project, and that's why we evaluate each request to enable pretranslation), also given we're still seeing a good amount of tiny errors.

You mean 7, right?

**Comment by flodolo** [comment]
Not sure if there's an issue on file already, but I'd like to be able to make small edits to a suggestion without attributing it to myself.

**Comment by mathjazz** [comment]
> Not sure if there's an issue on file already, but I'd like to be able to make small edits to a suggestion without attributing it to myself.

We have https://github.com/mozilla/pontoon/issues/2356, which is pretty close.

Which issue (in addition to #6) would you remove?

**Comment by mathjazz** [comment]
> Numbers: 3, 4, 11 (Bryan's)

@peiying2 I am not clear what do you mean by these 3 issues. Are you saying they should be removed?

In case my original message was confusing, please note that we are not voting for the 3 features yet, we are just deciding what's on the ballot.

**Comment by peiying2** [comment]
> > Numbers: 3, 4, 11 (Bryan's)
> 
> @peiying2 I am not clear what do you mean by these 3 issues. Are you saying they should be removed?
> 
> In case my original message was confusing, please note that we are not voting for the 3 features yet, we are just deciding what's on the ballot.

My bad - I thought we needed to vote out of these. But after re-reading your message, you were asking us to review it and add new proposals. Didn't mean to confuse you. Can I remove my comment, :D?

**Comment by mathjazz** [comment]
Since we're past the deadline, I'll close this now. The final list is at the top.

Thanks all for your feedback!
