### ISSUE TITLE
Pick 10 features for the 2025 Pontoon survey

### ISSUE THREAD

**Issue by mathjazz** [mozilla-l10n/pm-projects#354]
We need to select 10 features for the community to vote on in the 2025 Pontoon survey.
We'll commit to implementing the 2 or 3 top-voted features.

Here's my proposed list:
1. https://github.com/mozilla/pontoon/issues/2232
1. https://github.com/mozilla/pontoon/issues/2276
1. https://github.com/mozilla/pontoon/issues/2255
1. https://github.com/mozilla/pontoon/issues/2059
1. https://github.com/mozilla/pontoon/issues/2790
1. https://github.com/mozilla/pontoon/issues/2036
1. https://github.com/mozilla/pontoon/issues/2363
1. https://github.com/mozilla/pontoon/issues/2183
1. https://github.com/mozilla/pontoon/issues/2055
1. https://github.com/mozilla/pontoon/issues/2037

The first three are [(2023 runner-ups)](https://github.com/mozilla-l10n/pm-projects/issues/352).
The fourth is a [(2022 runner-ups)](https://github.com/mozilla/pontoon/issues/2355).
The fifth is my personal favourite. :)

**Please let me know if we should remove some of the items and provide a replacement in the comments below.**

Here's are some candidates that I didn't put one the list, but you might disagree:
1. https://github.com/mozilla/pontoon/issues/2928
2. https://github.com/mozilla/pontoon/issues/3150
3. https://github.com/mozilla/pontoon/issues/3203
4. https://github.com/mozilla/pontoon/issues/3254
5. https://github.com/mozilla/pontoon/issues/2383

**Comment by flodolo** [comment]
I feel like 3 is an edge case that would benefit a limited number of locales.

What's the practical use case for 6? None of the strings mentioned in the issue are stand-alone, so I see more risks than benefits.

I would prefer 1 and 5 in the second list to be on the first list. Do we know how many users used comments in 2024, and what's the average number of comments/user?

**Comment by mathjazz** [comment]
> What's the practical use case for 6? None of the strings mentioned in the issue are stand-alone, so I see more risks than benefits.

I think the issue description is not great. This one probably also mostly benefits the locales that benefit from 3.

> I would prefer 1 and 5 in the second list to be on the first list. Do we know how many users used comments in 2024, and what's the average number of comments/user?

264 users submitted 2197 comments so far this year.

**Comment by bcolsson** [comment]
I forget if this is something on our radar, but in terms of improvements for the translator experience I think this would be big:
1. https://github.com/mozilla/pontoon/issues/2125

**Comment by mathjazz** [comment]
> I forget if this is something on our radar, but in terms of improvements for the translator experience I think this would be big:
> 
>     1. [Make machinery usable for complex strings mozilla/pontoon#2125](https://github.com/mozilla/pontoon/issues/2125)

Yup, this is already a KR for 2025.

**Comment by Delphine** [comment]
I’d deprioritize 8 and 10 from the first list. Personally, I’m more into 1 and 4 from the second list instead and to replace.

**Comment by peiying2** [comment]
1 in the second batch

**Comment by mathjazz** [comment]
Thank for the feedback on such a short notice!

Since 3 additional features were suggested to be added and 4 to be removed, I kept #3, since it's a runner-up from last year. So this is the final list:

1. https://github.com/mozilla/pontoon/issues/2232
1. https://github.com/mozilla/pontoon/issues/2276
1. https://github.com/mozilla/pontoon/issues/2255
1. https://github.com/mozilla/pontoon/issues/2059
1. https://github.com/mozilla/pontoon/issues/2790
1. https://github.com/mozilla/pontoon/issues/2363
1. https://github.com/mozilla/pontoon/issues/2055
1. https://github.com/mozilla/pontoon/issues/2928
1. https://github.com/mozilla/pontoon/issues/3254
1. https://github.com/mozilla/pontoon/issues/2383
