### ISSUE TITLE
Paris Logistics

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#45]
- [x] Identify & book venue location
- [x] Identify & book hotel for localizers
- [x] Book travel for localizers
- [ ] Find & book restaurants or catering for 2 lunches & 3 dinners.
- [x] Identify visa needs.
- [ ] Identify transportation needs and make necessary arrangements.
- [ ] Get name tags and gear for localizers.
- [ ] Identify possible cultural activities.
- [x] Create Telegram group.

**Comment by mozillamarcia** [comment]
Perhaps we want to add getting the password for the Mozilla Instagram account from Sierra? That would a good weekend to takeover the account.

**Comment by mozillamarcia** [comment]
We already contacted Sierra regarding the Instagram account so that is covered.

**Comment by gueroJeff** [comment]
Could @Delphine and @TheoChevalier give an update about the food item on the list please? Also, I think it's sufficient to just include at the end of the wiki a list of possible sight seeing opportunities about how to see them.

**Comment by TheoChevalier** [comment]
Delphine said she had identified restaurants from what’s been suggested on the pad, and was about to call them (I think you said next week @Delphine, IIRC?)
For meals in the office, we’re still waiting for confirmation that Kosher food will be provided (should get confirmation by end of week), the rest is ok

**Comment by Delphine** [comment]
Yes I've postponed calling the restaurants until the end of the week because of visa cancellations. I'll call on Friday :)
