### ISSUE TITLE
Berlin Logistics

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#47]
- [x] Identify & book venue location
- [x] Identify & book hotel for localizers
- [x] Book travel for localizers
- [ ] Find & book restaurants or catering for 2 lunches & 3 dinners.
- [x] Identify visa needs.
- [ ] Identify transportation needs and make necessary arrangements.
- [x] Get name tags and gear for localizers.
- [x] Identify possible cultural activities.
- [x] Create Telegram group.

**Comment by gueroJeff** [comment]
Possible options for lunches: catering to the office.
Possible options for dinners:
**Friday**
- Office catering
- Buffet

**Saturday**
- Walking tour of Berlin street food.
- http://michelbergerhotel.com/de/restaurant
- http://www.seoulkitchen.de
- http://beta.mutzenbacher-berlin.de/speisekarte/
- http://www.restaurant-volt.de/index.php?article_id=2
- https://www.kurhaus-korsakow.de/en/food-and-drinks/meals/
- http://lemonleaf.de/

**Sunday**
- http://michelbergerhotel.com/de/restaurant
- http://www.seoulkitchen.de
- http://beta.mutzenbacher-berlin.de/speisekarte/
- http://www.restaurant-volt.de/index.php?article_id=2
- https://www.kurhaus-korsakow.de/en/food-and-drinks/meals/
- http://lemonleaf.de/

**Comment by flodolo** [comment]
Side note: we should make sure about payment methods, I remember having a lot of issues with credit cards in Berlin.
