### ISSUE TITLE
Kolkata Logistics

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#48]
- [x] Identify & book venue location
- [x] Identify & book hotel for localizers
- [x] Book travel for localizers
- [x] Find & book restaurants or catering for 2 lunches & 3 dinners.
- [x] Identify visa needs.
- [x] Identify transportation needs and make necessary arrangements.
- [x] Get name tags and gear for localizers.
- [x] Identify possible cultural activities.
- [x] Create Telegram group.

**Comment by gueroJeff** [comment]
From meeting on September 1st:
- Meeting place should be in at the hotel.
- Transportation (arrange shuttle for localizers coming from outside of India [ask hotel if they have shuttle service], those traveling within India should grab a cab and reimburse the expense)
- Hotel needs to serve breakfast and provide shuttle between airport and hotel

**Comment by gueroJeff** [comment]
@birajkarmakar

**Comment by gueroJeff** [comment]
Hotels near the airport are hard to find. The closest with availability is a Howard Johnson for $120/night in New Town Square. Regenta Orko's Kolkata in East Kolkata might be an option. The rest appear to be in the city center on the East side of the river.

**Comment by gueroJeff** [comment]
Cultural activity: 5:30PM to about 8:30PM on one day

**Comment by gueroJeff** [comment]
We'll need 10 single rooms, 5 double rooms. 20 total people have registered + 4 l10n-drivers = 24 total

**Comment by gueroJeff** [comment]
We'll need 10 single rooms, 5 double rooms. 20 total people have registered + 4 l10n-drivers = 24 total

**Comment by birajkarmakar** [comment]
We need 11 single rooms and 6 double rooms.

**Comment by gueroJeff** [comment]
I have the email ready to send to ProTravel for them to begin booking itineraries and lodging (sorry, it's just easier for me to make the arrangements this way).

@birajkarmakar I need you to have the locals that need hotels register in the form. I'll send it through Telegram. I need them to do this within the next two days please.

**Comment by gueroJeff** [comment]
Email sent to ProTravel.

**Comment by gueroJeff** [comment]
Now that ProTravel has begun booking travel, lodging, and venue, we need to identify some lunch and dinner options for 26 people. @birajkarmakar can you help with that please?

**Comment by birajkarmakar** [comment]
I will definitely help you. But I think after booking lodging and venue, we will see this because we need to take care about distance.

**Comment by gueroJeff** [comment]
Good point, I had forgotten about that.

**Comment by gueroJeff** [comment]
@birajkarmakar would you be able to visit the Senses Hotel in the next couple of days? ProTravel has spoken to them and they appear to be a good option for lodging and meeting. http://senseshotel.in/

**Comment by balapandu222** [comment]
@birajkarmakar , I discussed few drawbacks of Hotel Senses with @gueroJeff yesterday on messenger.  I was there in this Senses Hotel for couple of days in Kolkata around 1 year back. 
- It was far from airport and its located was in a busy place. 
- It will be better if we can choose near to the airport, it helps in decreasing cost price of up & down cab services. I see 16+ Kms from airport.
- This senses hotel is located at mixed places colleges, some IT companies around, local market, etc. Not a cozy and cleanliness area. My rating was 2.5/5, but services will be poor to my concern.

It will be great, If you go and check once. 
Thank you.

**Comment by balapandu222** [comment]
@gueroJeff  What about Swissotel and Howard Johnson hotels ?

**Comment by gueroJeff** [comment]
Howard Johnson does not have meeting space. ProTravel didn't mention Swissotel, which makes me think that they weren't a good fit. I'll follow up though to be sure.

**Comment by gueroJeff** [comment]
We are proceeding with Swissotel for both lodging and venue as the pricing they quoted to ProTravel was within our budget.

http://www.swissotel.com/hotels/kolkata/

Now we need to begin looking at dining options for Saturday and Sunday. One thing we did in Berlin that was easy was following the All Hands model: give everyone their budgeted allowance for meals and let them organize themselves. I don't think this is necessarily a good option for this event. Thoughts?

**Comment by birajkarmakar** [comment]
For outing, we may choose these http://www.ecoparknewtown.com/index.php. Need your feedback. 

BTW from Kolkata only two people are attending, so total room would be 10 Single rooms and 6 Double rooms.

**Comment by birajkarmakar** [comment]
BTW total people 26, if we book 10 single rooms then we need 8 double rooms.

Is not it @gueroJeff ?

**Comment by gueroJeff** [comment]
Some of those are rooms for l10n-drivers, which we've arranged ourselves
through egencia.

**Comment by gueroJeff** [comment]
That could be fun, my only concern is how much time that might require. Is
there a culturally important site to see/tour that's near by?

**Comment by gueroJeff** [comment]
Venue, lodging, flights, lunches, breakfasts are all booked.

**Comment by birajkarmakar** [comment]
It's not culturally important but it's like fun place. It's tourism park.  we need at least 2-3 hours.

**Comment by peiying2** [comment]
@birajkarmakar regarding cultural activity, is there an option B? In case not everyone is into it, is there cultural activity unique to this part of India or the city?  For instance, in Taipei, we had people going to night markets and others going to a tea house, so we split up based on interests. In Malaysia, we had dinner at a place where folk songs and dances were performed.
