### ISSUE TITLE
Taipei Invitations

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#53]
- [x] Define invitation criteria
- [x] Create invite list according to defined invitation criteria (3 per locale)
- [x] Get approval from locale leaders
- [x] Send out invitations

**Comment by gueroJeff** [comment]
Invite criteria based: 
- Recent translation activity (3 months)
- Leading/managing community l10n projects
- New localizers with recent activity and a unique perspective
- Vocal participation in communication channels
- Testing Pontoon

**Comment by gueroJeff** [comment]
Invite list created based on above criteria: https://docs.google.com/spreadsheets/d/1VtcdRFp1GANJGVG41KF67xJaARXEqahPVmj7C1NfrDU/edit#gid=872242690

**Comment by nth10sd** [comment]
An extra criteria could also be people who have organised a hackathon in the past, whom we feel would add value in going to another hackathon, for them to share experiences (good/bad/improvements) in terms of how to make future event organisation better.

**Comment by peiying2** [comment]
We now have the final list of people who registered to the event: 28 volunteers from 12 communities, including last year's lead organizer.

**Comment by gueroJeff** [comment]
All done! Thanks everyone!
