### ISSUE TITLE
Migrate Firefox (Nightly) to Pontoon

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#97]
Given the information about the next deadline for this project, it is the assignee's decision when to schedule the migration for this project so that it does not add risk to its l10n delivery.

Next merge day: 20 September
https://mozilla.locamotion.org/projects/firefox/

## Shipping locales

- [x] ach
- [x] af
- [x] an
- [x] ar
- [x] as
- [x] bn-BD
- [x] br
- [x] bs
- [x] ca
- [x] cak
- [x] cy
- [x] dsb
- [ ] en-ZA
- [x] eu
- [x] fa
- [x] ff
- [x] ga-IE
- [x] gd
- [x] gn
- [x] hi-IN
- [x] hr
- [x] hsb
- [x] hu
- [x] hy-AM
- [x] is
- [x] kk
- [x] kn
- [x] lt
- [x] mai
- [x] ml
- [x] mr
- [x] ne-NP
- [x] or
- [x] pt-PT
- [x] ro
- [x] son
- [x] ta
- [x] ur
- [x] uz
- [x] xh

## Others

- [ ] ak
- [ ] am
- [ ] arn
- [ ] bcl
- [ ] bm
- [ ] bo
- [ ] cbk
- [ ] ckb
- [ ] co
- [ ] crh
- [ ] ctu
- [ ] doi
- [ ] dz
- [ ] en-IE
- [ ] fj
- [ ] fo
- [ ] frp
- [ ] fur
- [ ] got
- [ ] gv
- [ ] haw
- [ ] hch
- [ ] ht
- [ ] hto
- [ ] hus
- [ ] ilo
- [ ] ixl
- [ ] jbo
- [ ] jv
- [ ] kok
- [ ] krc
- [ ] ku
- [ ] kw
- [ ] ky
- [ ] lb
- [ ] lg
- [ ] mg
- [ ] mn
- [ ] mni
- [ ] nch
- [ ] ncj
- [ ] nd
- [ ] neb
- [ ] nqo
- [ ] nso
- [ ] om
- [ ] pbb
- [ ] pms
- [ ] prs
- [ ] ps
- [ ] quy
- [ ] quz
- [ ] roa-ES-val
- [ ] rw
- [ ] sa
- [ ] sah
- [ ] sat
- [ ] sc
- [ ] sco
- [ ] sd
- [ ] shn
- [ ] sm
- [ ] ss
- [ ] su
- [ ] sw
- [ ] szl
- [ ] ti
- [ ] tk
- [ ] tn
- [ ] toj
- [x] trs
- [ ] tsz
- [ ] tt-RU
- [ ] tzh
- [ ] tzo
- [ ] ug
- [ ] wa
- [ ] yo
- [ ] yua
- [x] zam
- [ ] zu

**Comment by flodolo** [comment]
Ignored locales:
* en-ZA
