### ISSUE TITLE
Migrate Firefox Health Report to Pontoon

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#99]
Given the information about the next deadline for this project, it is the assignee's decision when to schedule the migration for this project so that it does not add risk to its l10n delivery.

Next release date: None
https://mozilla.locamotion.org/projects/fhr/

## Complete locales

- [x] ach
- [x] ar
- [x] as
- [x] bn-BD
- [x] br
- [x] bs
- [x] cak
- [x] cy
- [x] dsb
- [x] en-ZA
- [x] ga-IE
- [x] hi-IN
- [x] hsb
- [x] mai
- [x] ml
- [x] or
- [x] son
- [x] ta
- [x] ur
- [x] uz
- [x] xh

## In-progress locales

- [x] af
- [ ] ak
- [x] ff
- [x] gn
- [ ] lg
- [ ] mn
- [x] ne-NP
- [ ] sah

**Comment by flodolo** [comment]
For Pei's happiness, this one is probably mine too (we always considered it as part of Firefox).

Of the pending locales:
* We should remove unsupported locales from the repository (af, lg, mn, sah), in a pull request so it's trackable.
* We have content for af, ff, gn, ne-NP.

This one is probably the project we should start from.

**Comment by flodolo** [comment]
Looks like kn was enabled in both…

Didn't bother to move some of the incomplete locales (not shipping), since I've discovered that FHR is scheduled for removal soon.
https://bugzilla.mozilla.org/show_bug.cgi?id=1352497
